# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2dc61e388c0209e807a4fde46b081c7cd5d7ec0fe41b989dc845b5d5b84873410d815bb4e7d96dce0fc532177b7f17f3a040a12277f5e02b284ccf95bc881bd
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] || 'rundfunk-testing.eu.auth0.com' %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] || '3NSVbVwiVABkv6uS7vRzH0sY7mqmlzOG' %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] || '9K_-9dVpUMJhEhT301VlnqlgFBNkBTsvuLN_u1ZHGaHghE7eIq6cFOhjzlfI0eMf' %>
  auth0_api_client_id: <%= ENV["AUTH0_API_CLIENT_ID"] || 'FS3tvqobXzYREsy09NVdkdwnSntXcCvk' %>
  auth0_api_client_secret:  <%= ENV["AUTH0_API_CLIENT_SECRET"] || 'dXM5Nngj1uCf4xdX8_YxbiWe42plmswlDVZ7cDibCrDlOVLKcuXF6SgD1qrGgQYQ' %>

test:
  secret_key_base: 0711ba736507b8311b9fb0e18cabb178fcf8f4dd5612b547aa0773c820d6c66a64d51e9e417314bb5c7e51eeab69202d44a176d2ef31f7e415674da03c9ed15b
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] || 'rundfunk-testing.eu.auth0.com' %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] || '3NSVbVwiVABkv6uS7vRzH0sY7mqmlzOG' %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] || '9K_-9dVpUMJhEhT301VlnqlgFBNkBTsvuLN_u1ZHGaHghE7eIq6cFOhjzlfI0eMf' %>
  auth0_api_client_id: <%= ENV["AUTH0_API_CLIENT_ID"] || 'FS3tvqobXzYREsy09NVdkdwnSntXcCvk' %>
  auth0_api_client_secret:  <%= ENV["AUTH0_API_CLIENT_SECRET"] || 'dXM5Nngj1uCf4xdX8_YxbiWe42plmswlDVZ7cDibCrDlOVLKcuXF6SgD1qrGgQYQ' %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_domain: rundfunk-mitbestimmen.eu.auth0.com
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
  auth0_api_client_id: <%= ENV["AUTH0_API_CLIENT_ID"] %>
  auth0_api_client_secret:  <%= ENV["AUTH0_API_CLIENT_SECRET"] %>
