language: ruby
sudo: required
dist: trusty
rvm:
  - 2.3.1
env:
  - TRAVIS_NODE_VERSION="6.2.1"
services:
  - postgresql
addons:
  apt:
    sources:
       - google-chrome
    packages:
    - google-chrome-stable

before_install:
  #http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser

    #http://stackoverflow.com/questions/42210295/travis-unable-to-find-chromedriver
  - wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver

  # http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
  - cd frontend
  - npm config set spin false
  - npm install -g bower
  - npm install -g ember-cli
  - ember --version
  - bower --version
  - npm --version
  - node --version
  - chromedriver --version
  - cd ..

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd backend
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:schema:load
  - cd ..
  - cd frontend
  - ember build
  - cd ..

install:
  - bundle
  - cd frontend
  - npm install
  - bower install
  - cd ..
  - cd backend
  - cd ..


script:
  - bundle exec rake
