language: ruby
rvm:
  - 2.3.1
services:
  - postgresql
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - cp backend/config/database.travis.yml backend/config/database.yml
