version: '3'
services:
  sidekiq:
    image: rundfunk-mitbestimmen-sidekiq
    build:
      context: ./backend
    depends_on:
      - redis
      - db
    command: bundle exec sidekiq
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USERNAME=postgres
      - REDIS_URL=redis://redis:6379
  frontend:
    environment:
      - PORT=4200
    command: node production-server.js
