version: '3'
services:
  frontend:
    image: rundfunk-mitbestimmen-frontend
    build:
      context: ./frontend
    ports:
      - "${EMBER_PORT}:4200" # server
      - 49153:49153 # live reload
      - 7357:7357 # test server
    volumes:
      - ./frontend/app:/frontend/app
      - ./frontend/config:/frontend/config
      - ./frontend/public:/frontend/public
      - ./frontend/tests:/frontend/tests
      - ./frontend/translations:/frontend/translations
      - ./frontend/package.json:/frontend/package.json
      - ./frontend/ember-cli-build.js:/frontend/ember-cli-build.js
      - ./frontend/testem.js:/frontend/testem.js
    environment:
      - "API_HOST=http://localhost:3000"
    command: ember server
  backend:
    image: rundfunk-mitbestimmen-backend
    build:
      context: ./backend
    ports:
      - "${RAILS_PORT}:3000"
    volumes:
      - ./backend/Gemfile:/backend/Gemfile
      - ./backend/Gemfile.lock:/backend/Gemfile.lock
      - ./backend/Rakefile:/backend/Rakefile
      - ./backend/app:/backend/app
      - ./backend/config:/backend/config
      - ./backend/config.ru:/backend/config.ru
      - ./backend/db/migrate:/backend/db/migrate
      - ./backend/db/views:/backend/db/views
      - ./backend/db/schema.rb:/backend/db/schema.rb
      - ./backend/db/seeds.rb:/backend/db/seeds.rb
      - ./backend/lib:/backend/lib
      - ./backend/public:/backend/public
      - ./backend/spec:/backend/spec
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USERNAME=postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    command: "bin/rails server -b 0.0.0.0"
  sidekiq:
    image: rundfunk-mitbestimmen-sidekiq
    build:
      context: ./backend
    depends_on:
      - redis
      - db
    command: bundle exec sidekiq
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USERNAME=postgres
      - REDIS_URL=redis://redis:6379
  db:
    image: postgres:9.6
  redis:
    image: redis:3.2.0
